/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    'users.index': [];
    'users.store': [];
    'users.show': [
      {
        name: 'user';
        required: true;
        binding: 'id';
      },
    ];
    'users.update': [
      {
        name: 'user';
        required: true;
        binding: 'id';
      },
    ];
    'users.destroy': [
      {
        name: 'user';
        required: true;
        binding: 'id';
      },
    ];
    'turfs.index': [];
    'turfs.store': [];
    'turfs.show': [
      {
        name: 'turf';
        required: true;
        binding: 'id';
      },
    ];
    'turfs.update': [
      {
        name: 'turf';
        required: true;
        binding: 'id';
      },
    ];
    'turfs.destroy': [
      {
        name: 'turf';
        required: true;
        binding: 'id';
      },
    ];
    'players.index': [];
    'players.store': [];
    'players.show': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.update': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.destroy': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'teams.index': [];
    'teams.store': [];
    'teams.show': [
      {
        name: 'team';
        required: true;
        binding: 'id';
      },
    ];
    'teams.update': [
      {
        name: 'team';
        required: true;
        binding: 'id';
      },
    ];
    'teams.destroy': [
      {
        name: 'team';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.index': [];
    'match-sessions.store': [];
    'match-sessions.show': [
      {
        name: 'match_session';
        required: true;
      },
    ];
    'match-sessions.update': [
      {
        name: 'match_session';
        required: true;
      },
    ];
    'match-sessions.destroy': [
      {
        name: 'match_session';
        required: true;
      },
    ];
    'game-matches.index': [];
    'game-matches.store': [];
    'game-matches.show': [
      {
        name: 'game_match';
        required: true;
      },
    ];
    'game-matches.update': [
      {
        name: 'game_match';
        required: true;
      },
    ];
    'game-matches.destroy': [
      {
        name: 'game_match';
        required: true;
      },
    ];
    'match-events.index': [];
    'match-events.store': [];
    'match-events.show': [
      {
        name: 'match_event';
        required: true;
      },
    ];
    'match-events.update': [
      {
        name: 'match_event';
        required: true;
      },
    ];
    'match-events.destroy': [
      {
        name: 'match_event';
        required: true;
      },
    ];
    'queue-logic.index': [];
    'queue-logic.store': [];
    'queue-logic.show': [
      {
        name: 'queue_logic';
        required: true;
      },
    ];
    'queue-logic.update': [
      {
        name: 'queue_logic';
        required: true;
      },
    ];
    'queue-logic.destroy': [
      {
        name: 'queue_logic';
        required: true;
      },
    ];
    'team-players.index': [];
    'team-players.store': [];
    'team-players.show': [
      {
        name: 'team_player';
        required: true;
      },
    ];
    'team-players.update': [
      {
        name: 'team_player';
        required: true;
      },
    ];
    'team-players.destroy': [
      {
        name: 'team_player';
        required: true;
      },
    ];
    'turfs.players.index': [
      {
        name: 'turf';
        required: true;
      },
    ];
    'turfs.match-sessions.index': [
      {
        name: 'turf';
        required: true;
      },
    ];
    'players.match-sessions': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.available-teams': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'players.join-team': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.leave-team': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.team-status': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.payment-history': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'players.can-join-team': [
      {
        name: 'player';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.teams.index': [
      {
        name: 'matchSession';
        required: true;
      },
    ];
    'match-sessions.game-matches.index': [
      {
        name: 'matchSession';
        required: true;
      },
    ];
    'match-sessions.queue-logic.index': [
      {
        name: 'matchSession';
        required: true;
      },
    ];
    'match-sessions.queue-status': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.start': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.stop': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.add-player-to-team': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.set-game-result': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    'teams.players.index': [
      {
        name: 'team';
        required: true;
      },
    ];
    'teams.game-matches.index': [
      {
        name: 'team';
        required: true;
      },
    ];
    'game-matches.events.index': [
      {
        name: 'gameMatch';
        required: true;
      },
    ];
    'users.turfs.index': [
      {
        name: 'user';
        required: true;
      },
    ];
    'users.players.index': [
      {
        name: 'user';
        required: true;
      },
    ];
    'payments.initialize': [];
    'payments.verify': [];
    'payments.history': [];
    'payments.suggested-amount': [];
    'payments.show': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'payments.cancel': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'match-sessions.payment-stats': [
      {
        name: 'matchSession';
        required: true;
        binding: 'id';
      },
    ];
    welcome: [];
    dashboard: [];
    'payment.create': [];
    'payment.initialize': [];
    'payment.history': [];
    'payment.success': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'payment.failed': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'payment.verify': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'payment.cancel': [
      {
        name: 'payment';
        required: true;
        binding: 'id';
      },
    ];
    'payment.callback': [];
    'profile.edit': [];
    'profile.update': [];
    'profile.destroy': [];
    'password.edit': [];
    'password.update': [];
    appearance: [];
    register: [];
    login: [];
    'password.request': [];
    'password.email': [];
    'password.reset': [
      {
        name: 'token';
        required: true;
      },
    ];
    'password.store': [];
    'verification.notice': [];
    'verification.verify': [
      {
        name: 'id';
        required: true;
      },
      {
        name: 'hash';
        required: true;
      },
    ];
    'verification.send': [];
    'password.confirm': [];
    logout: [];
    'storage.local': [
      {
        name: 'path';
        required: true;
      },
    ];
  }
}
export {};
